# ----
# Site

title: Programming Contest
email: paris.programming.contest@gmail.com
description: "Learning, coding, computing, and sharing together"
baseurl: "" # site subpath
url: "https://programming-contest.github.io" 
twitter_username: glegoux
github_username:  glegoux

# -----
# Build

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
